name: sehrgutachten
description: 'Ausarbeitungen der Wissenschaftlichen Dienste des Bundestags'

pipeline:

  init:
    method: sehrgutachten:seed
    params:
      url: https://www.bundestag.de/ajax/filterlist/de/dokumente/ausarbeitungen/474644-474644
      limit: 10
      startdate: !ENV ${STARTDATE}
      startfield: date
      enddate: !ENV ${ENDDATE}
      endfield: date
    handle:
      pass: fetch

  fetch:
    method: fetch
    handle:
      pass: parse

  parse:
    method: sehrgutachten:parse
    handle:
      fetch: fetch
      download: download

  download:
    method: fetch
    handle:
      pass: store

  store:
    method: directory
    params:
      path: data_incremental
